environments:
  dev:
    api_version: 3a2ef8575e8fd51b656ee1a1177e6157b88a61ab
    web_version: fa55f9769003f187f2661d5ee18456a29f2a8bab
    sentry_release: Убрать сохранение префикса cloudinary в БД (#483)
  stage:
    enabled: false
    version: v2.13.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
