environments:
  dev:
    api_version: 49c12e630f29392402e6bd2f61a671641809b8cf
    web_version: 54dab61d7b81f163849f2043f57a39431a39a9ac
    sentry_release: "⬆️ Bump python from 3.12.0 to 3.12.3 (№528)"
  stage:
    enabled: false
    version: v2.16.0
    web_version: v2.15.0
  prod:
    version: v2.16.0
    web_version: v2.15.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
