environments:
  dev:
    api_version: 8e53b96bfc6c1da981ba3d6dfcb9fa897b31f43a
    web_version: 2a7828677d921e29eef654c55db695292159e6b6
    sentry_release: "⬆️ Bump google-api-python-client from 2.138.0 to 2.139.0 (№637)"
    platform_version: 496ee487477e306e401e17b88708502d06155519
  stage:
    enabled: false
    version: v2.16.1
    web_version: pre-v2.16.0
  prod:
    version: v2.16.1
    web_version: v2.17.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
certManager:
  version: v1.14.5
vault:
  version: 0.28.0
