environments:
  dev:
    api_version: e350db881d5c03d82e86b72c74eb988e4a0e3143
    web_version: b7e835c5973e8cd1bc3c8ce273ce1e671a7f86a9
    sentry_release: "Не работает добавление тега (#517)"
  stage:
    enabled: false
    version: v2.16.0
    web_version: v2.15.0
  prod:
    version: v2.16.0
    web_version: v2.15.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
