environments:
  dev:
    api_version: 7ede62c54091aebfee348e55f2a11d23fa63caba
    web_version: 4d72b63edf1286c1fa7a71425dd2b67ce22733fe
    sentry_release: ":recycle: Refactor code in user registration tests by mocking CalAuthService.register. :art: Improve structure--format of code in UsersRegisterTest class. :wrench: Update docker-compose.yml and docker--docker-compose.base.yml to modify network configurations."
  stage:
    enabled: false
    version: v2.15.0
  prod:
    version: v2.15.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
