environments:
  dev:
    api_version: e06796953726d51edcad4c7f406d53f9a68e5db2
    web_version: 2a7828677d921e29eef654c55db695292159e6b6
    sentry_release: "fix build cache"
  stage:
    enabled: true
    version: v2.16.0
    web_version: v2.16.0
  prod:
    version: v2.16.0
    web_version: v2.15.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
certManager:
  version: v1.14.5
vault:
  version: 0.28.0
