environments:
  dev:
    api_version: 1f6682ea5b7296c2f4e4dcb6b465364ff2ab9f08
    web_version: 2a7828677d921e29eef654c55db695292159e6b6
    sentry_release: "⬆️ Bump pozil--auto-assign-issue from 1.14.0 to 2.0.0 (№598)"
    platform_version: 496ee487477e306e401e17b88708502d06155519
  stage:
    enabled: false
    version: v2.16.1
    web_version: pre-v2.16.0
  prod:
    version: v2.16.1
    web_version: v2.17.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
certManager:
  version: v1.14.5
vault:
  version: 0.28.0
