environments:
  dev:
    api_version: 444f5f9b0adce67e0db76331111df451b3985f04
    web_version: 2a7828677d921e29eef654c55db695292159e6b6
    sentry_release: "Синхронизация учеток + slug c Cal.com (№503)"
    platform_version: 9582476fc1f498946084f03973c6ae9b07117f88
  stage:
    enabled: false
    version: v2.16.1
    web_version: pre-v2.16.0
  prod:
    version: v2.16.1
    web_version: v2.17.0
argocd:
  version: 5.46.8
sealedSecrets:
  version: 2.13.0
metricsServer:
  version: 3.11.0
ingressNginx:
  version: 4.7.2
reloader:
  version: 1.0.46
prometheusStack:
  version: 51.10.0
certManager:
  version: v1.14.5
vault:
  version: 0.28.0
